var linux = (function () {

	// Source for a lot of the data: http://busybox.net/downloads/BusyBox.html
	// data also taken from man pages

	var busyBoxCommands = 'acpid addgroup adduser adjtimex ar arp arping ash awk basename beep blkid brctl bunzip2 bzcat bzip2 cal cat catv chat chattr chgrp chmod chown chpasswd chpst chroot chrt chvt cksum clear cmp comm cp cpio crond crontab cryptpw cut date dc dd deallocvt delgroup deluser depmod devmem df dhcprelay diff dirname dmesg dnsd dnsdomainname dos2unix dpkg du dumpkmap dumpleases echo ed egrep eject env envdir envuidgid expand expr fakeidentd false fbset fbsplash fdflush fdformat fdisk fgrep find findfs flash_lock flash_unlock fold free freeramdisk fsck fsck.minix fsync ftpd ftpget ftpput fuser getopt getty grep gunzip gzip hd hdparm head hexdump hostid hostname httpd hush hwclock id ifconfig ifdown ifenslave ifplugd ifup inetd init inotifyd insmod install ionice ip ipaddr ipcalc ipcrm ipcs iplink iproute iprule iptunnel kbd_mode kill killall killall5 klogd last length less linux32 linux64 linuxrc ln loadfont loadkmap logger login logname logread losetup lpd lpq lpr ls lsattr lsmod lzmacat lzop lzopcat makemime man md5sum mdev mesg microcom mkdir mkdosfs mkfifo mkfs.minix mkfs.vfat mknod mkpasswd mkswap mktemp modprobe more mount mountpoint mt mv nameif nc netstat nice nmeter nohup nslookup od openvt passwd patch pgrep pidof ping ping6 pipe_progress pivot_root pkill popmaildir printenv printf ps pscan pwd raidautorun rdate rdev readlink readprofile realpath reformime renice reset resize rm rmdir rmmod route rpm rpm2cpio rtcwake run-parts runlevel runsv runsvdir rx script scriptreplay sed sendmail seq setarch setconsole setfont setkeycodes setlogcons setsid setuidgid sh sha1sum sha256sum sha512sum showkey slattach sleep softlimit sort split start-stop-daemon stat strings stty su sulogin sum sv svlogd swapoff swapon switch_root sync sysctl syslogd tac tail tar taskset tcpsvd tee telnet telnetd test tftp tftpd time timeout top touch tr traceroute true tty ttysize udhcpc udhcpd udpsvd umount uname uncompress unexpand uniq unix2dos unlzma unlzop unzip uptime usleep uudecode uuencode vconfig vi vlock volname watch watchdog wc wget which who whoami xargs yes zcat zcip'.split(' ');
	var allCommands = busyBoxCommands;
	/*
	var hardwareCommands = 'acpid beep blkid brctl clear df devmem dhcprelay du dumpkmap eject fbset fbsplash fdflush fdformat fdisk findfs flash_lock flash_unlock free freeramdisk fsck fsck.minix fsync getty hdparm hostid hostname hwclock inotifyd insmod ionice kdb_mode klogd ln loadkmap lpd lpq lpr lsmod mdev microcom mkdosfs mkfifo mkfs.minix mkfs.vfat mknod mkswap mktemp modprobe mount mountpoint mt nmeter raidautorun rdate rdev readlink readprofile realpath 
	var systemAdminCommands = 'addgroup adduser adjtimex cal chattr chgrp chmod chown chpasswd chpst chroot chrt chvt clear cp crond crontab cryptpw date dd deallocvt delgroup deluser devmem df dpkg echo env envdir enduidgid find free fuser id inotifyd insmod kill killall killall5 klogd last ln loadfont logger login lognam logread ls lsattr lsmod man mesg mkdir mkpasswd mv nice nmeter nohup openvt passwd patch pgrep pidof pivot_root pkill printenv ps pwd 
	var archiveCommands = 'ar bunzip2 bzcat bzip2 cat cksum cp cpio dd gunzip gzip install lzmacat lzop lzopcat makemime md5sum mkdirmv 
	var networkCommands = 'arp arping brctl chat dhcprelay dnsd dumpleases fakeidentd ftpd ftpget ftpput hostname httpd ifconfig ifdown ifenslave ifplugd ifup inetd ip ipaddr ipcalc iplink iproute iprule iptunnel losetup makemime nameif nc netstat nslookup ping popmaildir pscan rdate reformime 
	var dataProcessingCommands = 'awk basename bzcat cat cksum cmp comm cp cut dc diff dirname dos2unix echo env envdir expand expr find fold getopt grep hd head hexdump length less mktemp mv od printf 
	var commonLinuxCommands = 'cat chmod cp awk date diff echo find getopt grep gunzip gzip head less ln ls lsattr man md5sum mkdir mount more  pspwd';
	// Got up to renice in: http://busybox.net/downloads/BusyBox.html
	*/

	function whichCommand(doesThis, answer) {
		return function (quiz) {
			quiz.askQuestion({
				question:'Which command ' + doesThis + '?',
				answer:answer,
				choices:allCommands
			});
		};
	}

	var whichCommands = [
		whichCommand('listens to ACPI events', 'acpid'),
		whichCommand('spawns specific helpers on ACPI event arrival', 'acpid'),
		whichCommand('adds a group to the system', 'addgroup'),
		whichCommand('adds a user to a group', 'addgroup'),
		whichCommand('adds a user to the system', 'adduser'),
		whichCommand('reads system timebase parameters', 'adjtimex'),
		whichCommand('sets system timebase parameters', 'adjtimex'),
		whichCommand('extracts files from an ar archive', 'ar'),
		whichCommand('lists files in an ar archive', 'ar'),
		whichCommand('manipulates the ARP cache', 'arp'),
		whichCommand('sends ARP requests', 'arping'),
		whichCommand('sends ARP replies', 'arping'),
		//whichCommand('AWK','awk'),
		whichCommand('strips the directory path from a filename', 'basename'),
		whichCommand('strips the suffix from a filename', 'basename'),
		//whichCommand('','beep'),
		whichCommand('prints the UUIDs of all filesystems', 'blkid'),
		whichCommand('manages Ethernet bridges', 'brctl'),
		whichCommand('uncompresses files that have been compressed with the bzip2 algorithm', 'bunzip2'),
		whichCommand('uncompresses bzip2 files to stdout', 'bzcat'),
		whichCommand('compresses files with the bzip2 algorithm', 'bzip2'),
		whichCommand('displays a calendar', 'cal'),
		whichCommand('concatenates files and prints them to stdout', 'cat'),
		//whichCommand('display nonprinting characters as ^x or m-x','catv'),
		//whichCommand('interacts with a modem connected to stdin/stdout','chat'),
		whichCommand('changes file attributes on an ext2 fs', 'chattr'),
		whichCommand('changes the group membership of a file', 'chgrp'),
		whichCommand('changes the mode of a file', 'chmod'),
		whichCommand('changes the owner and/or group of a file', 'chown'),
		whichCommand('changes the owner of a file', 'chown'),
		whichCommand('updates /etc/passwd with user:password from stdin', 'chpasswd'),
		whichCommand('changes the process state and run a program', 'chpst'),
		whichCommand('runs a program with the root directory set to newroot', 'chroot'),
		whichCommand('manipulates the real-time attributes of a process', 'chrt'),
		whichCommand('changes the foreground virtual terminal', 'chvt'),
		whichCommand('calculates the CRC32 checksums of files', 'cksum'),
		whichCommand('clears the terminal screen', 'clear'),
		//whichCommand('compares files','cmp'),
		//whichCommand('compares files','comm'),
		whichCommand('copies a source file to a destination file', 'cp'),
		whichCommand('copies files', 'cp'),
		whichCommand('copies directories', 'cp'),
		whichCommand('creates a CPIO archive', 'cpio'),
		whichCommand('lists files from a CPIO archive', 'cpio'),
		whichCommand('extracts files from a CPIO archive', 'cpio'),
		//whichCommand('FIX','crond'),
		//whichCommand('FIX','crontab'),
		whichCommand('encrypts a password using crypt(3)', 'cryptpw'),
		whichCommand('prints selected fields from each input file to standard output', 'cut'),
		whichCommand('displays time', 'date'),
		whichCommand('displays date', 'date'),
		whichCommand('sets the time', 'date'),
		whichCommand('sets the date', 'date'),
		//whichCommand('tiny rpn calculator','dc'),
		//whichCommand('copies a file with converting and formatting','dd'),
		whichCommand('deallocates unused virtual terminal', 'deallocvt'),
		whichCommand('deletes a group from the system', 'delgroup'),
		whichCommand('deletes a user from a group', 'delgroup'),
		whichCommand('deletes a user from the system', 'deluser'),
		whichCommand('reads or from physical address', 'devmem'),
		whichCommand('writes to a physical address', 'devmem'),
		whichCommand('prints filesystem usage statistics', 'df'),
		whichCommand('relays dhcp requests between clients and server', 'dhcprelay'),
		whichCommand('compares files line by line and shows the differences between them', 'diff'),
		whichCommand('strips non-directory suffix from a filename', 'dirname'),
		whichCommand('prints the kernel ring buffer', 'dmesg'),
		whichCommand('controls the kernel ring buffer', 'dmesg'),
		whichCommand('runs a small static dns server daemon', 'dnsd'),
		whichCommand('converts a file in-place from dos to unix format', 'dos2unix'),
		whichCommand('installs Debian packages', 'dpkg'),
		whichCommand('removes Debian packages', 'dpkg'),
		whichCommand('manages Debian packages', 'dpkg'),
		whichCommand('summarizes disk space used for each file and/or directory', 'du'),
		whichCommand('prints a binary keyboard translation table to standard output', 'dumpkmap'),
		whichCommand('displays DHCP leases granted by udhcpd', 'dumpleases'),
		whichCommand('prints the specified args to stdout', 'echo'),
		//whichCommand('ed','ed'),
		whichCommand('ejects the specified device (defaults to /dev/cdrom)', 'eject'),
		whichCommand('prints the current environment or runs a program after setting up the specified environment', 'env'),
		whichCommand('sets various environment variables as specified by files in the directory', 'envdir'),
		whichCommand('sets $uid to the account\'s uid and $gid to the account\'s gid then runs a program', 'envuidgid'),
		whichCommand('converts tabs to spaces and writes to standard output', 'expand'),
		whichCommand('prints the value of expression to standard output', 'expr'),
		whichCommand('provides a fake ident (auth) service', 'fakeidentd'),
		whichCommand('returns an exit code of false (1)', 'false'),
		whichCommand('shows and modifies the frame buffer settings', 'fbset'),
		//whichCommand('options:','fbsplash'),
		whichCommand('forces the floppy disk drive to detect disk changes', 'fdflush'),
		whichCommand('formats the floppy disk', 'fdformat'),
		whichCommand('changes the partition table', 'fdisk'),
		whichCommand('searches for files', 'find'),
		whichCommand('finds a filesystem device based on a label or UUID', 'findfs'),
		whichCommand('locks part or all of an mtd device', 'flash_lock'),
		whichCommand('unlocks an mtd device', 'flash_unlock'),
		whichCommand('wraps lines in each file writing to standard output', 'fold'),
		whichCommand('displays the amount of free and used system memory', 'free'),
		whichCommand('frees all memory used by the specified ramdisk', 'freeramdisk'),
		whichCommand('checks and repairs the filesystems', 'fsck'),
		whichCommand('checks the minix filesystem', 'fsck.minix'),
		//whichCommand('options:','fsync'),
		whichCommand('anonymous FTP server', 'ftpd'),
		whichCommand('retrieves a remote file via ftp', 'ftpget'),
		whichCommand('stores a local file on a remote machine via ftp', 'ftpput'),
		whichCommand('finds processes which use files or ports', 'fuser'),
		//whichCommand('options:','getopt'),
		whichCommand('opens a tty, prompt for a login name, then invoke /bin/login', 'getty'),
		whichCommand('searches for pattern in each file or standard input', 'grep'),
		whichCommand('uncompresses files (or standard input)', 'gunzip'),
		whichCommand('compresses files (or standard input)', 'gzip'),
		whichCommand('is an alias for hexdump -c', 'hd'),
		//whichCommand('options:','hdparm'),
		whichCommand('prints the first 10 lines of a file', 'head'),
		whichCommand('displays file or standard input in a user specified format', 'hexdump'),
		whichCommand('prints out a unique 32-bit identifier for the machine', 'hostid'),
		whichCommand('gets or sets the hostname or the dns domain name', 'hostname'),
		whichCommand('listens for incoming http requests', 'httpd'),
		whichCommand('queries and sets the hardware clock (rtc)', 'hwclock'),
		whichCommand('prints information about user or the current user', 'id'),
		whichCommand('configures a network interface', 'ifconfig'),
		//whichCommand('options:','ifdown'),
		whichCommand('configures network interfaces for parallel routing', 'ifenslave'),
		//whichCommand('network interface plug detection daemon','ifplugd'),
		//whichCommand('options:','ifup'),
		whichCommand('listens for network connections and launch programs', 'inetd'),
		whichCommand('is the parent of all processes', 'init'),
		whichCommand('runs a program on filesystem changes.', 'inotifyd'),
		whichCommand('loads the specified kernel modules into the kernel', 'insmod'),
		whichCommand('copies files and sets attributes', 'install'),
		whichCommand('changes i/o scheduling class and priority', 'ionice'),
		//whichCommand('FIX','ip'),
		//whichCommand('FIX','ipaddr'),
		whichCommand('calculates ip network settings from a ip address', 'ipcalc'),
		//whichCommand('upper-case options mqs remove an object by shmkey value. lower-case options remove an object by shmid value.','ipcrm'),
		//whichCommand('ipcs [[-smq] -i shmid] | [[-asmq] [-tcplu]]','ipcs'),
		//whichCommand('FIX','iplink'),
		//whichCommand('FIX','iproute'),
		//whichCommand('blah','iprule'),
		//whichCommand('xx','iptunnel'),
		whichCommand('reports or sets the keyboard mode', 'kbd_mode'),
		whichCommand('sends a signal (default: term) to given pids', 'kill'),
		whichCommand('sends a signal (default: term) to given processes', 'killall'),
		whichCommand('sends a signal (default: term) to all processes outside current session', 'killall5'),
		whichCommand('is the kernel logger', 'klogd'),
		whichCommand('shows a listing of the last users that logged into the system', 'last'),
		whichCommand('prints a string\'s length', 'length'),
		whichCommand('views a file or list of files', 'less'),
		whichCommand('creates a link to the specified target(s)', 'ln'),
		whichCommand('loads a console font from standard input', 'loadfont'),
		whichCommand('loads a binary keyboard translation table from standard input', 'loadkmap'),
		whichCommand('writes message to the system log', 'logger'),
		whichCommand('begins a new session on the system', 'login'),
		whichCommand('prints the name of the current user', 'logname'),
		whichCommand('shows messages in syslogd\'s circular buffer', 'logread'),
		//whichCommand('options:','losetup'),
		//whichCommand('FIX','lpd'),
		//whichCommand('options:','lpq'),
		//whichCommand('options:','lpr'),
		whichCommand('lists the contents of a directory', 'ls'),
		whichCommand('lists the attributes of a file on an ext2 filesystem', 'lsattr'),
		whichCommand('lists the currently loaded kernel modules', 'lsmod'),
		whichCommand('uncompresses LZMA files to stdout', 'lzmacat'),
		//whichCommand('lzop [-cfvd123456789cf] [file]...','lzop'),
		//whichCommand('lzopcat [-vcf] [file]...','lzopcat'),
		whichCommand('creates multipart mime-encoded message from files', 'makemime'),
		whichCommand('formats and displays a page from the manual', 'man'),
		whichCommand('prints or checks md5 checksums', 'md5sum'),
		//whichCommand('mdev [-s]','mdev'),
		//whichCommand('xx','mesg'),
		whichCommand('copues bytes for stdin to tty and from tty to stdout', 'microcom'),
		whichCommand('creates a directory', 'mkdir'),
		whichCommand('makes a fat32 filesystem', 'mkdosfs'),
		whichCommand('creates a named pipe (identical to `mknod name p`)', 'mkfifo'),
		whichCommand('makes a minix filesystem', 'mkfs.minix'),
		whichCommand('makes a fat32 filesystem', 'mkfs.vfat'),
		whichCommand('creates a special file (block, character, or pipe)', 'mknod'),
		whichCommand('encrypts the password using crypt(3)', 'mkpasswd'),
		whichCommand('prepares a block device to be used as swap partition', 'mkswap'),
		whichCommand('creates a temporary file with a name based on template and print its name', 'mktemp'),
		//whichCommand('options:','modprobe'),
		whichCommand('views file or standard input one screenful at a time', 'more'),
		whichCommand('mounts a filesystem', 'mount'),
		whichCommand('checks if the directory is a mountpoint', 'mountpoint'),
		whichCommand('controls magnetic tape drive operation', 'mt'),
		whichCommand('renames source to destination', 'mv'),
		whichCommand('moves source files to a destination directory', 'mv'),
		whichCommand('renames network interface while it in the down state', 'nameif'),
		//whichCommand('options:','nc'),
		whichCommand('displays networking information', 'netstat'),
		whichCommand('runs a program with modified scheduling priority', 'nice'),
		whichCommand('monitors system in real time', 'nmeter'),
		whichCommand('runs a program immune to hangups, with output to a non-tty', 'nohup'),
		whichCommand('queries the nameserver for the ip address of the given host', 'nslookup'),
		whichCommand('writes an unambiguous representation, octal bytes by default, of file to standard output', 'od'),
		whichCommand('starts a program on a new virtual terminal', 'openvt'),
		whichCommand('changes the user\'s password', 'passwd'),
		//whichCommand('patch [-p num] [-i diff] [-r] [-n]','patch'),
		whichCommand('displays processes selected by a regular expression pattern', 'pgrep'),
		whichCommand('lists pids of all processes with names that match names', 'pidof'),
		whichCommand('sends ICMP echo_request packets to network hosts', 'ping'),
		whichCommand('sends ICMP echo_request packets to network hosts', 'ping6'),
		whichCommand('moves the current root file system to put_old and make new_root the new root file system', 'pivot_root'),
		whichCommand('sends a signal to processes selected by regular expression pattern', 'pkill'),
		whichCommand('fetches content of remote mailbox to local maildir', 'popmaildir'),
		whichCommand('prints all or some of the environment variables', 'printenv'),
		whichCommand('formats and print arguments according to format', 'printf'),
		whichCommand('reports process status', 'ps'),
		whichCommand('scans a host and prints all open ports', 'pscan'),
		whichCommand('prints the full filename of the current working directory', 'pwd'),
		whichCommand('tells the kernel to automatically search and start raid arrays', 'raidautorun'),
		whichCommand('gets and possibly sets the system date and time from a remote host', 'rdate'),
		whichCommand('prints the device node associated with the filesystem mounted at /', 'rdev'),
		whichCommand('displays the value of a symlink', 'readlink'),
		//whichCommand('options:','readprofile'),
		whichCommand('returns the absolute pathnames of given argument', 'realpath'),
		whichCommand('parses a mime-encoded message', 'reformime'),
		whichCommand('changes the priority of a running processes', 'renice'),
		whichCommand('resets the screen', 'reset'),
		whichCommand('resizes the screen', 'resize'),
		whichCommand('removes (unlink) the file(s)', 'rm'),
		whichCommand('removes the directory if it is empty', 'rmdir'),
		whichCommand('unloads the specified kernel modules from the kernel', 'rmmod'),
		whichCommand('edits kernel routing tables', 'route'),
		whichCommand('manipulates RPM packages', 'rpm'),
		whichCommand('outputs a CPIO archive of an RPM file', 'rpm2cpio'),
		whichCommand('enters a system sleep state until specified wakeup time', 'rtcwake'),
		whichCommand('runs a bunch of scripts in a directory', 'run-parts'),
		whichCommand('finds the current and previous system runlevel', 'runlevel'),
		whichCommand('starts and monitors a service and optionally an appendant log service', 'runsv'),
		whichCommand('starts a runsv process for each subdirectory', 'runsvdir'),
		whichCommand('receives a file using the xmodem protocol', 'rx'),
		//whichCommand('options:','script'),
		whichCommand('plays back typescripts, using timing information', 'scriptreplay'),
		//whichCommand('options:','sed'),
		whichCommand('reads email from stdin and sends it', 'sendmail'),
		whichCommand('prints numbers from first to last in steps of increment', 'seq'),
		//whichCommand('personality may be:','setarch'),
		whichCommand('redirects the system console output to a device (default: /dev/tty)', 'setconsole'),
		whichCommand('loads a console font', 'setfont'),
		whichCommand('sets entries into the kernel\'s scancode-to-keycode map, allowing unusual keyboards to generate usable keycodes', 'setkeycodes'),
		whichCommand('redirects the kernel output to a console', 'setlogcons'),
		whichCommand('runs a program in a new session', 'setsid'),
		whichCommand('sets a UID and GID to the account\'s UID and GID, removing all supplementary groups and runs a program', 'setuidgid'),
		whichCommand('prints or check sha1 checksums', 'sha1sum'),
		whichCommand('prints or check sha256 checksums', 'sha256sum'),
		whichCommand('prints or check sha512 checksums', 'sha512sum'),
		whichCommand('shows keys pressed', 'showkey'),
		whichCommand('attaches network interface(s) to serial line(s)', 'slattach'),
		whichCommand('pauses for a time equal to the total of the args given, where each arg can have an optional suffix of (s)econds, (m)inutes, (h)ours, or (d)ays', 'sleep'),
		whichCommand('sets soft resource limits, then runs a program', 'softlimit'),
		whichCommand('sorts lines of text', 'sort'),
		//whichCommand('options:','split'),
		whichCommand('searches for a matching processes and starts or stops it', 'start-stop-daemon'),
		whichCommand('displays file or filesystem status', 'stat'),
		whichCommand('displays printable strings in a binary file', 'strings'),
		whichCommand('prints baud rate, line discipline, and deviations from stty sane', 'stty'),
		whichCommand('changes user id or becomes root', 'su'),
		whichCommand('is used for single user login', 'sulogin'),
		whichCommand('checksums and counts the blocks in a file', 'sum'),
		whichCommand('controls services monitored by runsv supervisor', 'sv'),
		whichCommand('continuously read log data from standard input, optionally filter log messages, and write the data to one or more automatically rotated logs', 'svlogd'),
		whichCommand('stops swapping on device', 'swapoff'),
		whichCommand('starts swapping on device', 'swapon'),
		whichCommand('frees initramfs and switches to another root file system', 'switch_root'),
		whichCommand('writes all buffered blocks to disk', 'sync'),
		whichCommand('configures kernel parameters at runtime', 'sysctl'),
		whichCommand('is the system logging deamon', 'syslogd'),
		whichCommand('concatenates file(s) and print them in reverse', 'tac'),
		whichCommand('prints the last 10 lines of each file to standard output', 'tail'),
		whichCommand('creates, extracts, or list files from a tar archive', 'tar'),
		whichCommand('sets or gets cpu affinity', 'taskset'),
		whichCommand('creates tcp socket, binds to ip:port and listens for an incoming connection then runs a program for each connection', 'tcpsvd'),
		whichCommand('copies standard input to each file and to standard output', 'tee'),
		whichCommand('connects to telnet server', 'telnet'),
		whichCommand('handles incoming telnet connections', 'telnetd'),
		whichCommand('checks file types and compares values', 'test'),
		whichCommand('transfers a file from/to a tftp server', 'tftp'),
		whichCommand('transfers a file on a tftp client\'s request', 'tftpd'),
		whichCommand('runs a program and reports resource usage is displayed when finished', 'time'),
		whichCommand('runs a program and sends sig to it if it is not done in a specific amount of time', 'timeout'),
		whichCommand('provides a view of process activity in real time', 'top'),
		whichCommand('updates the last-modified date on the given file', 'touch'),
		whichCommand('translates, squeezes, and/or deletse characters from standard input, writing to standard output', 'tr'),
		whichCommand('traces the route to host', 'traceroute'),
		whichCommand('returns an exit code of true (0)', 'true'),
		whichCommand('prints file name of standard input\'s terminal', 'tty'),
		whichCommand('prints dimension(s) of standard input\'s terminal, on error return 80x25', 'ttysize'),
		//whichCommand('xx','udhcpc'),
		whichCommand('is a dhcp server', 'udhcpd'),
		whichCommand('creates a udp socket, binds to ip:port and waits for incoming packets then runs a program for each packet', 'udpsvd'),
		whichCommand('unmounts a file systems', 'umount'),
		whichCommand('prints system information', 'uname'),
		whichCommand('uncompresses .z files', 'uncompress'),
		whichCommand('converts spaces to tabs, writing to standard output', 'unexpand'),
		whichCommand('discards duplicate lines', 'uniq'),
		whichCommand('converts file in-place from unix to dos format', 'unix2dos'),
		whichCommand('uncompresses file compressed with LZMA', 'unlzma'),
		//whichCommand('unlzop [-cfvcf] [file]...','unlzop'),
		whichCommand('extracts files from zip archives', 'unzip'),
		whichCommand('displays the time since the last boot', 'uptime'),
		whichCommand('pauses for n microseconds', 'usleep'),
		//whichCommand('uudecodes a file finds outfile name in uuencoded source unless -o is given','uudecode'),
		whichCommand('uuencodes a file to stdout', 'uuencode'),
		whichCommand('creates and removes virtual ethernet devices', 'vconfig'),
		whichCommand('edits files', 'vi'),
		whichCommand('locks a virtual terminal', 'vlock'),
		whichCommand('shows cd volume name of the device (default /dev/cdrom)', 'volname'),
		whichCommand('runs a program periodically', 'watch'),
		whichCommand('periodically writes to watchdog device dev', 'watchdog'),
		whichCommand('prints the line, word, and byte counts for a file', 'wc'),
		whichCommand('retrieves files via http or ftp', 'wget'),
		whichCommand('locates a command', 'which'),
		whichCommand('shows who is logged on', 'who'),
		whichCommand('prints the user name associated with the current effective user id', 'whoami'),
		whichCommand('runs a program on every item given by standard input', 'xargs'),
		whichCommand('repeatedly outputs a line with a string, or \'y\'', 'yes'),
		whichCommand('uncompresses a file to stdout', 'zcat'),
		whichCommand('manages a zeroconf ipv4 link-local address', 'zcip')
	];

	function any(quiz) {
		quiz.choose(whichCommands, 1)[0](quiz);
	}

	return {
		questions: {
			any: any,
			whichCommand: whichCommands
		},
		options: []
	};

})();
